/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SQL;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Empleados extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    Menu menu;
    Conexion c = new Conexion();
    boolean bandCambio = false;
    String ID = "";
    public Empleados(Menu jMenu) {
        initComponents();
        menu = jMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButVer = new javax.swing.JButton();
        jButVerVista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextIDEmpleado = new javax.swing.JTextField();
        jTextSexo = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextDomicilio = new javax.swing.JTextField();
        jTextSeccion = new javax.swing.JTextField();
        jTextCanHijos = new javax.swing.JTextField();
        jTextEstadoCiv = new javax.swing.JTextField();
        jTextFechaIng = new javax.swing.JTextField();
        jTextSueldo = new javax.swing.JTextField();
        jButAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextEmpleados = new javax.swing.JTextArea();
        jButVerVista1 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Empleados");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Empleados");

        jButVer.setText("Ver");
        jButVer.setToolTipText("Muestra toda la tabla");
        jButVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerActionPerformed(evt);
            }
        });

        jButVerVista.setText("Vista1 ");
        jButVerVista.setToolTipText("vista 1: Nombre, Sexo, Seccion y la cantidad de hijos");
        jButVerVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerVistaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("ID Empleado");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Sexo:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Apellido: ");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Nombre: ");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Domicilio: ");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Seccion: ");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Cantidad de hijos: ");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Estado civil:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Fecha ingreso:");
        jLabel11.setToolTipText("Año/Mes/Dia");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("Sueldo: ");

        jTextSexo.setToolTipText("(m/f)");

        jTextEstadoCiv.setToolTipText("casado, divorciado, soltero o viudo");

        jButAgregar.setText("Agregar");
        jButAgregar.setToolTipText("Trigger insertar, actualizar y eliminar: Notifica al encargado y envia correo en automatico");
        jButAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAgregarActionPerformed(evt);
            }
        });

        jTextEmpleados.setEditable(false);
        jTextEmpleados.setColumns(20);
        jTextEmpleados.setRows(5);
        jScrollPane1.setViewportView(jTextEmpleados);

        jButVerVista1.setText("Vista2");
        jButVerVista1.setToolTipText("vista 1: Nombre, Apellido, Fecha de ingreso, Seccion, Estado civil y Sueldo>600");
        jButVerVista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerVista1ActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextIDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButVer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButVerVista))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6))
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextSexo, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                                    .addComponent(jTextApellido)
                                                    .addComponent(jTextNombre))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButVerVista1)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jButAgregar)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(btnEliminar)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnModificar)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextDomicilio)
                                                            .addComponent(jTextSeccion)
                                                            .addComponent(jTextCanHijos))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel10)
                                                            .addComponent(jLabel13)
                                                            .addComponent(jLabel11))))))))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFechaIng)
                                    .addComponent(jTextEstadoCiv, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(jTextSueldo))))
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButVer)
                    .addComponent(jButVerVista)
                    .addComponent(jButVerVista1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButAgregar)
                        .addComponent(btnEliminar)
                        .addComponent(btnModificar))
                    .addComponent(jTextIDEmpleado, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jTextSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEstadoCiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFechaIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCanHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          this.dispose();
          menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerActionPerformed
        // TODO add your handling code here:
        String texto = "";
        try {
            c.ConectarBasedeDatos();
            String sql = "use Empresa "
            + "Select * from empleados";
            c.resultado = c.sentencia.executeQuery(sql);
         
            while(c.resultado.next()){
                texto += "ID Empleado = " + c.resultado.getInt("IDEmpleado")
                      +", Sexo = "+c.resultado.getString("sexo")
                      +", Apellido = "+c.resultado.getString("apellido")
                      +", Nombre = "+c.resultado.getString("nombre")
                      +", Domicilio = "+c.resultado.getString("domicilio")
                      +", Seccion = "+c.resultado.getString("seccion")
                      +", Cantidad de hijos = "+c.resultado.getString("cantidadhijos")
                      +", Estado civil = "+c.resultado.getString("estadocivil") 
                      +", Fecha de ingreso = "+c.resultado.getString("fechaingreso")
                      +", Sueldo = "+c.resultado.getString("sueldo")+"\n";
                }
            c.DesconectarBasedeDatos();
        }catch(SQLException ex){
            Logger.getLogger(Secciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextEmpleados.setText(texto);
    }//GEN-LAST:event_jButVerActionPerformed

    private void jButVerVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerVistaActionPerformed
        // TODO add your handling code here:
        String texto = "";
        try {
            c.ConectarBasedeDatos();
            String sql = "use Empresa "
            + "Select * from vista_empleados";
            c.resultado = c.sentencia.executeQuery(sql);
         
            while(c.resultado.next()){
                texto += "Nombre = "+c.resultado.getString("nombre")
                      +", Sexo = "+c.resultado.getString("sexo")
                      +", Seccion = "+c.resultado.getString("seccion")
                      +", Cantidad de hijos = "+c.resultado.getString("cantidadhijos")+"\n";
                }
            c.DesconectarBasedeDatos();
        }catch(SQLException ex){
            Logger.getLogger(Secciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextEmpleados.setText(texto);
    }//GEN-LAST:event_jButVerVistaActionPerformed

    private void jButVerVista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerVista1ActionPerformed
        // TODO add your handling code here:
         String texto = "";
        try {
            c.ConectarBasedeDatos();
            String sql = "use Empresa "
            + "Select * from empleados";
            c.resultado = c.sentencia.executeQuery(sql);
         
            while(c.resultado.next()){
                texto +="Nombre = "+c.resultado.getString("nombre")
                      +", Apellido = "+c.resultado.getString("apellido")
                      +", Fecha de ingreso = "+c.resultado.getString("fechaingreso")
                      +", Seccion = "+c.resultado.getString("seccion") 
                      +", Estado civil = "+c.resultado.getString("estadocivil") 
                      +", Sueldo = "+c.resultado.getString("sueldo")+"\n";          
                }
            c.DesconectarBasedeDatos();
        }catch(SQLException ex){
            Logger.getLogger(Secciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextEmpleados.setText(texto);
    }//GEN-LAST:event_jButVerVista1ActionPerformed

    private void jButAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAgregarActionPerformed
        // TODO add your handling code here:
        try{
        c.ConectarBasedeDatos();
        String sql="";
       
        sql = "use Empresa "
                + "insert into empleados values("
                + jTextIDEmpleado.getText()
                +",'"+jTextSexo.getText()+"'"
                +",'"+ jTextApellido.getText()+"'"
                +",'"+jTextNombre.getText()+"'"
                +",'"+jTextDomicilio.getText()+"'"
                +","+ jTextSeccion.getText()
                +","+ jTextCanHijos.getText()
                +",'"+jTextEstadoCiv.getText()+"'"
                +",'"+jTextFechaIng.getText()+"'"
                +","+jTextSueldo.getText()+");";
  
        c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(this, "El empleado se agregó correctamente");
        c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            Logger.getLogger(Secciones.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } 
    }//GEN-LAST:event_jButAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            // Conectamos a la base de datos 
            c.ConectarBasedeDatos();
           // Obtiene ID Empleado 
            String ID = JOptionPane.showInputDialog(null,"ID Empleado: ","Eliminar Empleado",JOptionPane.QUESTION_MESSAGE);
             // Generamos la sentencia sql, con los datos ingresados del empleado
            String sql = "use Empresa DELETE FROM empleados WHERE IDEmpleado = "+ID;
            // Se ejecuta la sentencia 
            c.sentencia.execute(sql);
            // se elimina de la tabla 
            jButVer.doClick();
            // Si se ejecutó correctamente, entonces notifica al usuario
            JOptionPane.showMessageDialog(null, "Empleado Eliminado");

           // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            // En caso de tener un error, lo notifica al usuario.
            JOptionPane.showMessageDialog(null, "Error al Eliminar Empleado");
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       // NOTA: Si no deja modificar es por los permisos que tiene el usuario, ver en Trigger.sql, en Permiso empleados. Si no permite hacer los cambios
       // eliminar el trigger usando drop trigger PermisoEmpleados
        // para introducir los datos 
        if(bandCambio == false){
         
        bandCambio = true;
        try {
            // Conecta a la base de datos 
            c.ConectarBasedeDatos();
            // Obtiene ID Empleado 
            ID = JOptionPane.showInputDialog(null,"ID Empleado: ","Eliminar Empleado",JOptionPane.QUESTION_MESSAGE);   
            // Creamos la sentencia 
            String sql = "use Empresa SELECT * FROM empleados WHERE IDEmpleado = "+ID;
            // La ejecutamos
            c.resultado = c.sentencia.executeQuery(sql);
            
            // Y lo pone en los jText
            while (c.resultado.next()) {
                jTextIDEmpleado.setText(c.resultado.getInt("IDEmpleado")+"");
                jTextSexo.setText(c.resultado.getString("sexo"));
                jTextApellido.setText(c.resultado.getString("apellido"));
                jTextNombre.setText(c.resultado.getString("nombre"));
                jTextDomicilio.setText(c.resultado.getString("domicilio"));
                jTextSeccion.setText(c.resultado.getInt("seccion")+"");
                jTextCanHijos.setText(c.resultado.getInt("cantidadhijos")+"");
                jTextEstadoCiv.setText(c.resultado.getString("estadocivil"));
                jTextFechaIng.setText(c.resultado.getString("fechaingreso"));
                jTextSueldo.setText(c.resultado.getInt("sueldo")+"");
            }
            // Desconecta la base de datos
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) { // en caso de tener un error lo notifica
            JOptionPane.showMessageDialog(null,ex.toString());
        }
        
        }
        else if(bandCambio == true){
        try {
            // Conectamos a la base de datos 
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql, con los datos ingresados de los txt
            String sql = "use Empresa "
                    + "UPDATE empleados SET "
                    + "IDEmpleado="+ jTextIDEmpleado.getText()+", "
                    + "sexo='"+ jTextSexo.getText()+"', "
                    + "apellido='"+ jTextApellido.getText()+"', "
                    + "nombre='"+ jTextNombre.getText()+"', "
                    + "domicilio='"+ jTextDomicilio.getText()+"', "
                    + "seccion="+ jTextSeccion.getText()+", "
                    + "cantidadhijos="+ jTextCanHijos.getText()+", "
                    + "estadocivil='"+ jTextEstadoCiv.getText()+"', "
                    + "fechaingreso='"+ jTextFechaIng.getText()+"', "
                    + "sueldo="+ jTextSueldo.getText()+" "
                    + "WHERE IDEmpleado="+ ID;
            
            // Se ejecuta la sentencia 
             c.sentencia.execute(sql);
            // Si se ejecutó correctamente, entonces notifica al usuario
            JOptionPane.showMessageDialog(null, "Empleado Modificado");
           bandCambio = false;
           // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            // En caso de tener un error, lo notifica al usuario.
            JOptionPane.showMessageDialog(null, "Error al Modificar Empleado");
             JOptionPane.showMessageDialog(null,ex);
        }
        }
    
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados(new Menu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButAgregar;
    private javax.swing.JButton jButVer;
    private javax.swing.JButton jButVerVista;
    private javax.swing.JButton jButVerVista1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextCanHijos;
    private javax.swing.JTextField jTextDomicilio;
    private javax.swing.JTextArea jTextEmpleados;
    private javax.swing.JTextField jTextEstadoCiv;
    private javax.swing.JTextField jTextFechaIng;
    private javax.swing.JTextField jTextIDEmpleado;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextSeccion;
    private javax.swing.JTextField jTextSexo;
    private javax.swing.JTextField jTextSueldo;
    // End of variables declaration//GEN-END:variables
}
