
package SQL;

import javax.swing.JOptionPane;

public class Herramientas extends javax.swing.JFrame {

    /**
     * Creates new form Herramientas
     */
    Menu menu;
    Conexion c = new Conexion();
    public Herramientas(Menu jMenu) {
        initComponents();
        menu = jMenu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButRegresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnCrearDB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnCrearTablaEmpleados = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnCrearTablaSecciones = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnCrearTrigger1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnInsertarEmpleados = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnInsertarSecciones = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnCrearTrigger2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnCrearTrigger3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEliminarTrigger1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnInsertarSecciones2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnCrearVE = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnCrearVE2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnCrearVE1 = new javax.swing.JButton();
        btnCrearVS1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jButRegresar.setBackground(new java.awt.Color(102, 153, 255));
        jButRegresar.setText("Regresar");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Herramientas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 153, 255))); // NOI18N

        jLabel8.setText("Crear Base de datos: ");

        btnCrearDB.setText("Crear");
        btnCrearDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDBActionPerformed(evt);
            }
        });

        jLabel9.setText("Crear Tabla empleados: ");

        btnCrearTablaEmpleados.setText("Crear");
        btnCrearTablaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTablaEmpleadosActionPerformed(evt);
            }
        });

        jLabel10.setText("Crear Tabla secciones: ");

        btnCrearTablaSecciones.setText("Crear");
        btnCrearTablaSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTablaSeccionesActionPerformed(evt);
            }
        });

        jLabel11.setText("Crear Tigger Permiso Empleados: ");

        btnCrearTrigger1.setText("Crear");
        btnCrearTrigger1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTrigger1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Insertar empleados ");

        btnInsertarEmpleados.setText("Crear");
        btnInsertarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarEmpleadosActionPerformed(evt);
            }
        });

        jLabel13.setText("Insertar secciones ");

        btnInsertarSecciones.setText("Crear");
        btnInsertarSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarSeccionesActionPerformed(evt);
            }
        });

        jLabel14.setText("Crear Tigger Permiso Secciones: ");

        btnCrearTrigger2.setText("Crear");
        btnCrearTrigger2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTrigger2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Crear Tigger Notificacion:");

        btnCrearTrigger3.setText("Crear");
        btnCrearTrigger3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTrigger3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Eliminar Trigger Empleados:");

        btnEliminarTrigger1.setText("Elimina");
        btnEliminarTrigger1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTrigger1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Eliminar Trigger Secciones:");

        btnInsertarSecciones2.setText("Elimina");
        btnInsertarSecciones2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarSecciones2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Crear Vista Empleados:");

        btnCrearVE.setText("Crear");
        btnCrearVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVEActionPerformed(evt);
            }
        });

        jLabel17.setText("Crear Vista Empleados 2:");

        btnCrearVE2.setText("Crear");
        btnCrearVE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVE2ActionPerformed(evt);
            }
        });

        jLabel18.setText("Elimina Vista Empleados:");

        jLabel19.setText("Elimina Vista Empleados 2:");

        btnCrearVE1.setText("Elimina");
        btnCrearVE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVE1ActionPerformed(evt);
            }
        });

        btnCrearVS1.setText("Elimina");
        btnCrearVS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVS1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearTrigger3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearTrigger2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearTablaSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearTablaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCrearDB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearTrigger1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsertarSecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarTrigger1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertarSecciones2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearVE2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearVE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearVE1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearVS1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnCrearDB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnCrearTablaEmpleados)
                    .addComponent(jLabel12)
                    .addComponent(btnInsertarEmpleados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnCrearTablaSecciones)
                    .addComponent(jLabel13)
                    .addComponent(btnInsertarSecciones))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnCrearTrigger1)
                    .addComponent(jLabel1)
                    .addComponent(btnEliminarTrigger1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btnCrearTrigger2)
                    .addComponent(jLabel2)
                    .addComponent(btnInsertarSecciones2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(btnCrearTrigger3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(btnCrearVE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(btnCrearVE2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(btnCrearVE1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(btnCrearVS1))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButRegresar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButRegresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_jButRegresarActionPerformed

    private void btnCrearDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDBActionPerformed
        try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para generar todos los productos
            String sql = "create database Empresa";

            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null,"Se creó correctamente la Base de datos Empresa");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_btnCrearDBActionPerformed

    private void btnCrearTablaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTablaEmpleadosActionPerformed
        try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para generar todos los empleados
            String sql = "use Empresa "
            + "create table empleados("
            + "IDEmpleado int,"
            + "sexo char(1) constraint CK_empleados_sexo check (sexo in ('f','m')),"
            + "apellido varchar(20),"
            + "nombre varchar(20),"
            + "domicilio varchar(30),"
            + "seccion int not null,"
            + "cantidadhijos tinyint constraint CK_empleados_hijos check (cantidadhijos>=0),"
            + "estadocivil char(10) constraint CK_empleados_estadocivil check (estadocivil in ('casado','divorciado','soltero','viudo')),"
            + "fechaingreso datetime, "
            + "constraint PK_empleados primary key (IDEmpleado),"
            + "sueldo decimal(6,2), "
            + "constraint FK_empleados_seccion sueldo decimal(6,2),"
            + "foreign key (seccion) references secciones(IDSeccion) on update cascade);";

            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null,"Se creó correctamente la tabla empleados");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_btnCrearTablaEmpleadosActionPerformed

    private void btnCrearTablaSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTablaSeccionesActionPerformed
        // TODO add your handling code here:
         try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para generar todos las secciones
            String sql = "use Empresa "
            + "CREATE TABLE secciones ( "
            + " IDSeccion int, "
            + "nombre varchar(20), "
            + "sueldo decimal(5,2), constraint CK_secciones_sueldo check (sueldo>=0),"
            + "constraint PK_secciones primary key (IDSeccion));";

            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null,"Se creó correctamente la tabla secciones");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_btnCrearTablaSeccionesActionPerformed

    private void btnCrearTrigger1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTrigger1ActionPerformed
        // TODO add your handling code here:
         try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para generar trigger para los permisos en empleados
            String sql = "use Empresa "
                    + "Create trigger PermisoEmpleados on empleados after insert, update as Raiserror ('Notificar a encargado',16,10); go";
            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null,"Se creó correctamente el permiso para empleados");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_btnCrearTrigger1ActionPerformed

    private void btnInsertarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarEmpleadosActionPerformed
        // TODO add your handling code here:
         try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para generar todos los empleados
            String sql = "use Empresa "+
            "insert into empleados values(1,'f','Lopez','Ana','Colon 123',1,2,'casado','1990-10-10',600);" +
            "insert into empleados values(2,'m','Lopez','Luis','Sucre 235',1,0,'soltero','1990-02-10',650);" +
            "insert into empleados values(3,'m','Gomez','Pablo','Bulnes 321',3,2,'casado','1998-10-09',900);" +
            "insert into empleados values(4,'m','Garcia','Marcos','Sarmiento 1234',2,3,'divorciado','1998-07-12',800);" +
            "insert into empleados values(5,'f','Perez','Laura','Peru 1254',3,3,'casado','2000-05-09',700);";

            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null,"Se insertó correctamente en la tabla empleados");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_btnInsertarEmpleadosActionPerformed

    private void btnInsertarSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarSeccionesActionPerformed
        // TODO add your handling code here:
        try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para generar todos las secciones
            String sql = "use Empresa " + 
                    "insert into secciones values(1,'Administracion',300);" +
                    "insert into secciones values(2,'Contaduría',400);" +
                    "insert into secciones values(3,'Sistemas',500);";

            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null,"Se insertó correctamente en la tabla secciones");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_btnInsertarSeccionesActionPerformed

    private void btnCrearTrigger2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTrigger2ActionPerformed
        // TODO add your handling code here:
        try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para generar trigger para los permisos en secciones
            String sql = "use Empresa "
                    + "Create trigger PermisoSecciones on secciones after insert, update as Raiserror ('Notificar a encargado',16,10); go";
            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null,"Se creó correctamente el permiso para secciones");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_btnCrearTrigger2ActionPerformed

    private void btnCrearTrigger3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTrigger3ActionPerformed
        // TODO add your handling code here:
        try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para generar trigger para notificar 
            String sql = "use Empresa "
                    + "create trigger IUD_Noti on secciones after insert, update, delete as "
                    + "EXEC msdb.dbo.sp_send_dbmail "
                    + "@profile_name = 'usuario',"
                    + "@recipients = 'alu.12131415@correo.itlalaguna.edu.mx',"
                    + "@body = 'No olvide imprimir un informe.',"
                    + "@subject = 'Recordatorio';"
                    + "go";
            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null, "Se creó correctamente");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnCrearTrigger3ActionPerformed

    private void btnEliminarTrigger1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTrigger1ActionPerformed
        // TODO add your handling code here:
         try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para eliminar trigger para los permisos en empleados
            String sql = "use Empresa "
                    + "drop trigger PermisoEmpleados";
            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null, "Se elimino correctamente");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnEliminarTrigger1ActionPerformed

    private void btnInsertarSecciones2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarSecciones2ActionPerformed
        // TODO add your handling code here:
        try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para eliminar trigger para los permisos en secciones
            String sql = "use Empresa "
                    + "drop trigger permisoSecciones";
            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null, "Se elimino correctamente");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnInsertarSecciones2ActionPerformed

    private void btnCrearVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVEActionPerformed
        // TODO add your handling code here:
         try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para la vista empleados
            String sql = "use Empresa "
                    + "create view vista_empleados as "
                    + "select (apellido+' '+e.nombre) as nombre,sexo, "
                    + "s.nombre as seccion, cantidadhijos "
                    + "from empleados as e "
                    + "join secciones as s "
                    + "on IDSeccion=seccion;";
            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null, "Se creó correctamente la vista empleados");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnCrearVEActionPerformed

    private void btnCrearVE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVE2ActionPerformed
        // TODO add your handling code here:
         try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para la vista empleados 2
            String sql = "use Empresa "
                    + "create view vista_empleados2 as "
                    + "select nombre, apellido,fechaingreso,seccion,estadocivil,sueldo "
                    + "from empleados "
                    + "where sueldo>=600 "
                    + "with check option;";
            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null, "Se creó correctamente la vista empleados 2");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnCrearVE2ActionPerformed

    private void btnCrearVE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVE1ActionPerformed
        // TODO add your handling code here:
        try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para eliminar vista empleados
            String sql = "use Empresa drop view vista_empleados;";
            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null, "Se elimino correctamente la vista empleados");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnCrearVE1ActionPerformed

    private void btnCrearVS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVS1ActionPerformed
        // TODO add your handling code here:
        try {
            c.ConectarBasedeDatos();
            // Generamos la sentencia sql para eliminar vista empleados
            String sql = "use Empresa drop view vista_empleados2;";
            // Se ejecuta la sentencia
            c.sentencia.execute(sql);
            JOptionPane.showMessageDialog(null, "Se elimino correctamente la vista empleados 2");
            // se desconecta de la base de datos para evitar errores
            c.DesconectarBasedeDatos();
        } catch (Exception ex) {
            // En caso de tener un error, lo notifica.
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnCrearVS1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Herramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Herramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Herramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Herramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Herramientas(new Menu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearDB;
    private javax.swing.JButton btnCrearTablaEmpleados;
    private javax.swing.JButton btnCrearTablaSecciones;
    private javax.swing.JButton btnCrearTrigger1;
    private javax.swing.JButton btnCrearTrigger2;
    private javax.swing.JButton btnCrearTrigger3;
    private javax.swing.JButton btnCrearVE;
    private javax.swing.JButton btnCrearVE1;
    private javax.swing.JButton btnCrearVE2;
    private javax.swing.JButton btnCrearVS1;
    private javax.swing.JButton btnEliminarTrigger1;
    private javax.swing.JButton btnInsertarEmpleados;
    private javax.swing.JButton btnInsertarSecciones;
    private javax.swing.JButton btnInsertarSecciones2;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
